runmode: debug
addr: :8080
name: apiserver
url: http://127.0.0.1:8080
max_ping_count: 10
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1024
  log_backup_count: 7

db:
  name: db_apiserver
  addr: 192.168.10.10:3306
  username: homestead
  password: secret
docker_db:
  name: db_apiserver
  addr: 192.168.10.10:3306
  username: homestead
  password: secret